### ISSUE TITLE
training code?

### ISSUE THREAD

**Issue by yxt132** [bytedance/res-adapter#3]
Do you plan to release the training code?

**Comment by jiaxiangc** [comment]
@yxt132 

We will continue to open source new model weights and support more ecologies so that users can use them conveniently.
However, we are not considering opening the ResAdapter training code for the time being, as it involves the company's interests.
If you want to know more details about the training of the model, you can read our [paper](https://arxiv.org/abs/2403.02084).

Thank you for your attention.
